
function [ft] = fitness(xn,N,Dataset)
    for i=1:N
        opt = trainingOptions('sgdm', ...
            'InitialLearnRate',xn(i,1), ...
            'Momentum', xn(i,2), ...
            'MaxEpochs',10, ...
            'Shuffle','every-epoch', ...
            'ValidationFrequency',10, ...
            'Verbose',false, ...
            'ExecutionEnvironment','auto', ...
            'Plots', 'none');
        ft(i) = deepLearning2(Dataset, opt);
    end
end